### ISSUE TITLE
Extracting year from extra info

### ISSUE THREAD

**Issue by JSDA123** [heerden/kodi-music-video-nfo#1]
The script works perfectly, thank you for sharing it!

Just wonering if it would be possible to populate the year value using info included between the parenthesis?  For example my music video files look like this:

`song - artist (foobar 170101).mkv`

I'm useless at python so hoping for some help to add the following to the nfo:

`<year>2017</year>`

In my case the dates in the filename always start with the last two digits of year (ie "17" for 2017) and to make things easier it is safe to assume all years are 2000 or later.

Any help would be greatly appreciated!

**Comment by heerden** [comment]
This is a good recommendation!

I added the year tag, which you can add in the yymmdd or yyyy format.

**Comment by JSDA123** [comment]
Hey that's exactly what I was looking for.  Thank you!
